# Generated by Django 3.1.2 on 2020-11-03 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0001_initial'),
        ('checkout', '0002_order_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='account_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='useraccount.useraccount'),
        ),
    ]
