# Generated by Django 3.1.2 on 2020-11-04 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_order_account_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='account_number',
            new_name='user_profile',
        ),
    ]
