# Generated by Django 3.1.2 on 2020-11-06 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0002_auto_20201104_1059'),
        ('wishlists', '0002_auto_20201106_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwishlist',
            name='user_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='useraccount.useraccount'),
        ),
    ]
