# Generated by Django 3.1.2 on 2020-11-06 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20201102_2237'),
        ('wishlists', '0003_auto_20201106_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwishlist',
            name='wished_products',
            field=models.ManyToManyField(related_name='userwishlists', to='products.Product'),
        ),
    ]
