# Generated by Django 3.1.2 on 2020-10-30 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20201025_0855'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-avail_for_pre_order']},
        ),
    ]
