# Generated by Django 3.1.2 on 2020-11-08 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20201108_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_of_dispatch',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
